---
################################################################################
# Craft CMS
################################################################################

site_repo_url: git@github.com:USERNAME/REPO.git

craft_env: "production"
craft_site_name:  "{{ project_name }}"
craft_host_url:   "{{ project_produ_domain }}.{{ project_produ_tld }}"
craft_site_url: "//{{ project_produ_domain }}.{{ project_produ_tld }}"
craft_base_url: "//{{ project_produ_domain }}.{{ project_produ_tld }}"
craft_base_path: "/"
craft_db_host: "{{ RDS_DB_ENDPOINT }}"
craft_db_user: "{{ RDS_DB_USERNAME }}"
craft_db_password: "{{ RDS_DB_PASSWORD }}"
craft_db_name: "{{ RDS_DB_NAME }}"
craft_db_schema: ""
craft_db_table_prefix: ""

################################################################################
# Nginx
################################################################################

nginx_vhosts:
  - listen: "80"
    server_name: "{{ craft_host_url }}"
    root: /site/public
    index: "index.php index.html index.htm"
    extra_parameters: |

      location ~ ^/(wp-login|wp-admin|wp-config|wp-content|wp-includes|(.*)\.exe) {
        return 301 https://wordpress.com/wp-login.php;
      }
      location / {
        try_files $uri $uri/ /index.php$is_args$args;
      }
      location ^~ /admin {
        try_files $uri $uri/ /index.php$is_args$args;
      }
      location ^~ /cpresources {
        try_files $uri $uri/ /index.php$is_args$args;
      }
      location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param CRAFT_ENV_ENVIRONMENT     "{{ craft_env }}";
        fastcgi_param CRAFT_ENV_DB_HOST         "{{ craft_db_host }}";
        fastcgi_param CRAFT_ENV_DB_NAME         "{{ craft_db_name }}";
        fastcgi_param CRAFT_ENV_DB_USER         "{{ craft_db_user }}";
        fastcgi_param CRAFT_ENV_DB_PASS         "{{ craft_db_password }}";
        fastcgi_param CRAFT_ENV_DB_SCHEMA       "{{ craft_db_schema }}";
        fastcgi_param CRAFT_ENV_DB_TABLE_PREFIX "{{ craft_db_table_prefix }}";
        fastcgi_param CRAFT_ENV_SITE_URL        "{{ craft_site_url }}";
        fastcgi_param CRAFT_ENV_BASE_URL        "{{ craft_base_url }}";
        fastcgi_param CRAFT_ENV_BASE_PATH       "{{ craft_base_path }}";
      }
      location ~ /\.ht {
        deny all;
      }

################################################################################
# MySQL Root Password on EC2. Not in use, but needs to be cyptic. != `root`.
################################################################################
mysql_root_password: "{{ craft_db_password }}"
################################################################################
#
################################################################################
