<?php

return [
      '*' => [
          // ------------------------------------------
          'siteUrl'  => getenv('CRAFT_ENV_SITE_URL'),
          'env' => getenv('CRAFT_ENV_ENVIRONMENT'),
          // ------------------------------------------
          'allowAutoUpdates' => false,
          'omitScriptNameInUrls' => true,
          'preventUserEnumeration' => true,
          'usePathInfo' => true,
          'useEmailAsUsername' => true,
          'enableCsrfProtection' => true,
          // ------------------------------------------
          // Set the environmental variables
          'environmentVariables' => array(
              'baseUrl'  => getenv('CRAFT_ENV_BASE_URL'),
              'basePath' => getenv('CRAFT_ENV_BASE_PATH'),
          ),
          // ------------------------------------------

      ],
      'production' => [
          // ------------------------------------------

          // ------------------------------------------
      ],
      'local' => [
          // ------------------------------------------
          'devMode' => true,
          'enableTemplateCaching' => false
          // ------------------------------------------
      ],
];


// Defaults

	// 'actionTrigger' => 'actions',
	// 'activateAccountSuccessPath' => '',
	// 'addTrailingSlashesToUrls' => false,
	// 'allowAutoUpdates' => true,
	// 'allowedFileExtensions' => '7z,aiff,asf,avi,bmp,csv,doc,docx,fla,flv,gif,gz,gzip,htm,html,jpeg,jpg,js,mid,mov,mp3,mp4,m4a,m4v,mpc,mpeg,mpg,ods,odt,ogg,ogv,pdf,png,potx,pps,ppsm,ppsx,ppt,pptm,pptx,ppz,pxd,qt,ram,rar,rm,rmi,rmvb,rtf,sdc,sitd,svg,swf,sxc,sxw,tar,tgz,tif,tiff,txt,vob,vsd,wav,webm,wma,wmv,xls,xlsx,zip',
	// 'allowSimilarTags' => false,
	// 'allowUppercaseInSlug' => false,
	// 'appId' => null,
	// 'autoLoginAfterAccountActivation' => false,
	// 'backupDbOnUpdate' => true,
	// 'baseCpUrl' => null,
	// 'blowfishHashCost' => 13,
	// 'cacheElementQueries' => true,
	// 'cacheDuration' => 'P1D',
	// 'cacheMethod' => 'file',
	// 'convertFilenamesToAscii' => false,
	// 'cooldownDuration' => 'PT5M',
	// 'cpTrigger' => 'admin',
	// 'csrfTokenName' => 'CRAFT_CSRF_TOKEN',
	// 'customAsciiCharMappings' => array(),
	// 'defaultCookieDomain' => '',
	// 'defaultCpLanguage' => '',
	// 'defaultFilePermissions' => 0664,
	// 'defaultFolderPermissions' => 0775,
	// 'defaultImageQuality' => 82,
	// 'defaultSearchTermOptions' => array(
	// 	'attribute' => null,
	// 	'exact' => false,
	// 	'exclude' => false,
	// 	'subLeft' => false,
	// 	'subRight' => false,
	// ),
	// 'defaultTemplateExtensions' => array('html', 'twig'),
	// 'defaultTokenDuration' => 'P1D',
	// 'defaultWeekStartDay' => 0,
	// 'deferPublicRegistrationPassword' => false,
	// 'devMode' => false,
	// 'elevatedSessionDuration' => 'PT5M',
	// 'enableCsrfProtection' => false,
	// 'enableTemplateCaching' => true,
	// 'environmentVariables' => array(),
	// 'errorTemplatePrefix' => '',
	// 'extraAllowedFileExtensions' => '',
	// 'filenameWordSeparator' => '-',
	// 'generateTransformsBeforePageLoad' => false,
	// 'imageDriver' => 'auto',
	// 'indexTemplateFilenames' => array('index'),
	// 'invalidLoginWindowDuration' => 'PT1H',
	// 'invalidUserTokenPath' => '',
	// 'isSystemOn' => null,
	// 'limitAutoSlugsToAscii' => false,
	// 'logDumpMethod' => 'var_export',
	// 'loginPath' => 'login',
	// 'logoutPath' => 'logout',
	// 'maxCachedCloudImageSize' => 2000,
	// 'maxInvalidLogins' => 5,
	// 'maxSlugIncrement' => 100,
	// 'maxUploadFileSize' => 16777216,
	// 'omitScriptNameInUrls' => 'auto',
	// 'overridePhpSessionLocation' => false,
	// 'pageTrigger' => 'p',
	// 'phpMaxMemoryLimit' => '256M',
	// 'phpSessionName' => 'CraftSessionId',
	// 'postCpLoginRedirect' => 'dashboard',
	// 'postLoginRedirect' => '',
	// 'preserveImageColorProfiles' => true,
	// 'preventUserEnumeration' => false,
	// 'privateTemplateTrigger' => '_',
	// 'purgePendingUsersDuration' => false,
	// 'rememberUsernameDuration' => 'P1Y',
	// 'rememberedUserSessionDuration' => 'P2W',
	// 'requireMatchingUserAgentForSession' => true,
	// 'requireUserAgentAndIpForSession' => true,
	// 'resourceTrigger' => 'cpresources',
	// 'restoreDbOnUpdateFailure' => true,
	// 'rotateImagesOnUploadByExifData' => true,
	// 'runTasksAutomatically' => true,
	// 'sendPoweredByHeader' => true,
	// 'setPasswordPath' => 'setpassword',
	// 'setPasswordSuccessPath' => '',
	// 'showBetaUpdates' => false,
	// 'siteName' => null,
	// 'siteUrl' => null,
	// 'slugWordSeparator' => '-',
	// 'suppressTemplateErrors' => false,
	// 'testToEmailAddress' => '',
	// 'timezone' => null,
	// 'translationDebugOutput' => false,
	// 'tokenParam' => 'token',
	// 'useCompressedJs' => true,
	// 'useEmailAsUsername' => false,
	// 'usePathInfo' => 'auto',
	// 'useSecureCookies' => 'auto',
	// 'useSslOnTokenizedUrls' => 'auto',
	// 'userSessionDuration' => 'PT1H',
	// 'useWriteFileLock' => 'auto',
	// 'useXSendFile' => false,
	// 'validateUnsafeRequestParams' => false,
	// 'validationKey' => null,
	// 'verificationCodeDuration' => 'P1D',
